# Morteza Project: IMU and xdf file

We have a file in XDF format containing kinematic IMU data. This format, due to its sampling method, helps ensure that the recording time for each sensor is identical and prevents timing discrepancies by synchronizing the recording timestamps.

Objective: To read and analyze the file.

In [46]:
# Basic Packages
import os

# xdf reader
import pyxdf # pip install pyxdf

# Analysis Packages
import numpy as np
import pandas as pd

# Plot Packages
import matplotlib.pyplot as plt
import seaborn as sns

# Static Package
import scipy.stats as stats

### PATH of input and output

In [ ]:
PATH = os.path.dirname(os.getcwd())
NAME_FOLDER_INPUT = r"data\raw\6. Mrteza Project IMU and xdf file"
NAME_FOLDER_OUTPUT = r"data\processed\6. Mrteza Project IMU and xdf file"

# Make input and output path
INPUT_PATH = os.path.join(PATH, NAME_FOLDER_INPUT)
INPUT_OUTPUT = os.path.join(PATH, NAME_FOLDER_OUTPUT)

### Read name of all file by `xdf` format

create one dataframe from name of all data   
create one column from name of dataframe   
`inf_all_sdf_data` is a dataframe from file name and name of each dataframe

In [44]:
# read name of each file as .xdf
name_all_file = [f for f in os.listdir(INPUT_PATH) if f.endswith(".xdf")]

# create datafram from name of data by .xdf
inf_all_sdf_data = pd.DataFrame(name_all_file, columns=["name_file"])

# create name of each dataframe
inf_all_sdf_data["name_df"] = (inf_all_sdf_data["name_file"].
                               str.replace(".xdf", "").
                               str.replace("-","_").
                               str.replace(" ", "_"))
inf_all_sdf_data

,name_file,name_df
0,sub-P001_ses-S001_task-Default_run-001_eeg.xdf,sub_P001_ses_S001_task_Default_run_001_eeg

### Read one data

In [64]:
# path of one data
path_read = os.path.join(INPUT_PATH, inf_all_sdf_data["name_file"].iloc[0])

# raed data
data, header = pyxdf.load_xdf(path_read)

In [65]:
header

{'info': defaultdict(list,
             {'version': ['1.0'], 'datetime': ['2026-05-22T12:48:04+0200']})}

In [73]:
len(data)

12

In [80]:
name_each_Xsens = []
for i in range(len(data)):
    name_each_Xsens.append(data[i]["info"]["name"])

In [144]:
data[6]['time_stamps']

array([], dtype=float64)

In [125]:
data[0].keys(), data[6].keys()

(dict_keys(['info', 'footer', 'time_series', 'time_stamps', 'clock_times', 'clock_values']),
 dict_keys(['info', 'footer', 'time_series', 'time_stamps', 'clock_times', 'clock_values']))

In [141]:
stream = data[0]
df = pd.DataFrame(stream['time_series'])
df.index = stream['time_stamps']
df.index.name = 'timestamp'
df.columns = [ch['label'][0] for ch in stream['info']['desc'][0]['channels'][0]['channel']]
df

,qw,qx,qy,qz,ax,ay,az,gx,gy,gz,packet_counter,sample_time_fine
timestamp,,,,,,,,,,,,
229501.472544,0.099020,0.005810,-0.002649,-0.995065,-0.090631,0.075291,9.776200,-0.008962,0.006068,-0.002955,12303.0,0.0
229501.482596,0.099021,0.005805,-0.002610,-0.995065,-0.083169,0.051323,9.751882,-0.006871,0.003363,-0.001430,12304.0,0.0
229501.492647,0.099018,0.005803,-0.002555,-0.995066,-0.091469,0.073681,9.776204,-0.010151,0.004301,-0.001368,12305.0,0.0
229501.502698,0.099004,0.005797,-0.002484,-0.995067,-0.101624,0.094862,9.751747,-0.013208,0.003712,-0.004408,12306.0,0.0
229501.512749,0.098985,0.005792,-0.002421,-0.995069,-0.115895,0.062052,9.752830,-0.011709,0.003993,-0.004440,12307.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...
229515.453850,0.083752,0.011817,-0.001658,-0.996415,-0.184272,0.071303,9.766708,0.003579,0.005374,-0.003182,13702.0,0.0
229515.463901,0.083762,0.011826,-0.001646,-0.996414,-0.172329,0.103592,9.766027,-0.001278,0.005996,0.001436,13703.0,0.0
229515.473952,0.083761,0.011856,-0.001644,-0.996414,-0.175751,0.049081,9.767643,0.001122,0.009563,-0.001724,13704.0,0.0
229515.484003,0.083763,0.011863,-0.001650,-0.996414,-0.185649,0.070797,9.742274,0.002044,0.005108,-0.000073,13705.0,0.0
229515.494055,0.083755,0.011869,-0.001647,-0.996414,-0.196624,0.094008,9.765696,0.000593,0.004745,-0.003201,13706.0,0.0

### Reading all data streams simultaneously.   
Using the `inf_all_sdf_data` DataFrame, we read the individual dataframes and create a specific dataset for each, named accordingly.

In [43]:
for file in inf_all_sdf_data["name_file"]:
    print(file)

sub-P001_ses-S001_task-Default_run-001_eeg.xdf