# Projektseminar - Charistoph

In [21]:
# Basic Packages
import os

# Analysis Packages
import numpy as np
import pandas as pd

# Plot Packages
import matplotlib.pyplot as plt
import seaborn as sns

# Static Package
import scipy.stats as stats

### PATH of input and output

In [3]:
PATH = os.path.dirname(os.getcwd())
NAME_FOLDER_INPUT = r"data\raw\7. Projektseminar - Charistoph- Real Time Radar\mmVitals-Projekt-main"
NAME_FOLDER_OUTPUT = r"data\processed\7. Projektseminar - Charistoph- Real Time Radar\mmVitals-Projekt-main"

# Make input and output path
INPUT_PATH = os.path.join(PATH, NAME_FOLDER_INPUT)
INPUT_OUTPUT = os.path.join(PATH, NAME_FOLDER_OUTPUT)

### Read name of all file by `bin` format

create one dataframe from name of all data   
create one column from name of dataframe   
`inf_all_sdf_data` is a dataframe from file name and name of each dataframe

In [18]:
# read name of each file as .bin
name_all_file = [f for f in os.listdir(INPUT_PATH) if f.endswith(".bin")]

# create datafram from name of data by .xdf
inf_all_df_data = pd.DataFrame(name_all_file, columns=["name_file"])

# create name of each dataframe
inf_all_df_data["name_df"] = (inf_all_df_data["name_file"].
                               str.replace(".xdf", "").
                               str.replace("-","_").
                               str.replace(" ", "_"))
inf_all_df_data

           name_file            name_df
0  adc_data_Test.bin  adc_data_Test.bin

In [20]:
PATH_BIN

'data\\raw\\7. Projektseminar - Charistoph- Real Time Radar\\mmVitals-Projekt-main\\adc_data_Test.bin'

In [29]:
PATH_BIN = os.path.join(INPUT_PATH, inf_all_df_data["name_file"].iloc[0])

with open(PATH_BIN, 'rb') as f:
    full_data = f.read()

data = np.fromfile(PATH_BIN, dtype=np.int16)
data

array([  53,  101,  124, ...,  -32, -359, -440],
      shape=(204800,), dtype=int16)

In [31]:

PATH_BIN = os.path.join(INPUT_PATH, inf_all_df_data["name_file"].iloc[0])

raw = np.fromfile(PATH_BIN, dtype=np.int16)

n_cols = 8   # یکی از گزینه‌ها را تست کن
df = pd.DataFrame(raw.reshape(-1, n_cols))

df

         0    1    2    3    4    5    6    7
0       53  101  124  157 -170 -371  184 -180
1       34  288 -451 -234  285  162   24   19
2      236  160  100  353 -315 -407  273 -183
3       32  326 -516 -207  316  300   -1   91
4      114   69  247  209 -134 -448  248    6
...    ...  ...  ...  ...  ...  ...  ...  ...
25595 -464 -599  587   38  -56  342 -222  168
25596  109 -312  646  624 -371 -308  406  353
25597 -431 -543  349  118 -339  117 -172  -70
25598  262  -97  377  767 -552 -553  596  286
25599 -626 -750  292    8 -546  -32 -359 -440

[25600 rows x 8 columns]